# .cargo/config.toml
[env]
SQLX_OFFLINE            = { value = "false", force = false }
PLATFORM_DATABASE_URL   = { value = "postgres://emakao:password@localhost:5432/emakao_platform", force = false }
TENANT_DATABASE_URL     = { value = "postgres://emakao:password@localhost:5432/emakao_tenant",   force = false }